---
name: Create PDF File

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4  # this checks out the repo in the ubuntu container
      - name: "Create a folder called output"
        run: |
          mkdir output
          cp Hubbs-William-Resume.md output
      # Downloading the binaries directly, because they are newer and work better, than the ones that come with Ubuntu latest.
      - name: "Install pandoc and wkhtmltopdf"
        run: |
          wget https://github.com/jgm/pandoc/releases/download/3.0.1/pandoc-3.0.1-1-amd64.deb
          wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-2/wkhtmltox_0.12.6.1-2.jammy_amd64.deb
          sudo apt install ./pandoc-3.0.1-1-amd64.deb
          sudo apt install ./wkhtmltox_0.12.6.1-2.jammy_amd64.deb

      - name: "Convert MD to HTML"
        run: |
          # https://www.linode.com/docs/guides/how-to-use-python-markdown-to-convert-markdown-to-html/
          if ! pip freeze | grep -q markdown; then
            pip install --upgrade markdown
          fi
          python ./md2html.py
          mv index.html output/Hubbs-William-Resume.html

      - name: "Convert HTML to PDF "
        run: |
            wkhtmltopdf --enable-local-file-access output/Hubbs-William-Resume.html output/Hubbs-William-Resume.pdf
      # run: |
      #     pandoc -standalone --output=output/resume.pdf --css=resume-stylesheet.css --from=markdown --to=pdf --pdf-engine=/usr/bin/wkhtmltopdf resume.md

      - uses: actions/upload-artifact@master
        with:  # basically this will put resume.md, resume.html, resume.pdf and resume-stylesheet.css in a zip file.
          name: Hubbs-William-Resume
          path: output
